version: '3.1'

services:
  db:
    image: mysql:8.0 
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/website-scripts/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - /var/log/website-logs/mysql:/var/log/mysql

  ghost1:
    image: ghost:latest
    environment:
      database__client: mysql
      database__connection__host: localhost
      database__connection__user: ${DB_USERNAME}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${WEBSITE1_DB_NAME}
    volumes:
      - ${WEBSITE1_FOLDER}:/var/lib/ghost/content/
      - /var/log/website-logs/ghost/${WEBSITE1_DB_NAME}:/var/log/ghost      
    ports:
      - "3001:2368"

  ghost2:
    image: ghost:latest
    environment:
      database__client: mysql
      database__connection__host: localhost
      database__connection__user: ${DB_USERNAME}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${WEBSITE2_DB_NAME}
    volumes:
      - ${WEBSITE2_FOLDER}:/var/lib/ghost/content
      - /var/log/website-logs/ghost/${WEBSITE2_DB_NAME}:/var/log/ghost      
    ports:
      - "3002:2368"

  ghost3:
    image: ghost:latest
    environment:
      database__client: mysql
      database__connection__host: localhost
      database__connection__user: ${DB_USERNAME}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${WEBSITE3_DB_NAME}
    volumes:
      - ${WEBSITE3_FOLDER}:/var/lib/ghost/content
      - /var/log/website-logs/ghost/${WEBSITE3_DB_NAME}:/var/log/ghost      
    ports:
      - "3003:2368"
      
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/website-scripts/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CERTS_PATH}:/etc/letsencrypt
      - /var/log/website-logs/nginx:/var/log/nginx

volumes:
  ghost1-data:
  ghost2-data:
  ghost3-data:
