name: Deploy Ghost Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment variables
        run: |
          echo "WEBSITE1_DOMAIN=${{ secrets.WEBSITE1_DOMAIN }}" >> .env
          echo "WEBSITE2_DOMAIN=${{ secrets.WEBSITE2_DOMAIN }}" >> .env
          echo "WEBSITE3_DOMAIN=${{ secrets.WEBSITE3_DOMAIN }}" >> .env
          echo "WEBSITE1_DB_NAME=${{ secrets.WEBSITE1_DB_NAME }}" >> .env
          echo "WEBSITE2_DB_NAME=${{ secrets.WEBSITE2_DB_NAME }}" >> .env
          echo "WEBSITE3_DB_NAME=${{ secrets.WEBSITE3_DB_NAME }}" >> .env
          echo "WEBSITE1_FOLDER=${{ secrets.WEBSITE1_FOLDER }}" >> .env
          echo "WEBSITE2_FOLDER=${{ secrets.WEBSITE2_FOLDER }}" >> .env
          echo "WEBSITE3_FOLDER=${{ secrets.WEBSITE3_FOLDER }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "CERTS_PATH=${{ secrets.CERTS_PATH }}" >> .env
          echo "EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}" >> .env
          
      - name: Copy all files to server
        uses: appleboy/scp-action@master      
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./*"
          target: "/home/website-scripts"

      - name: Create cronjob on remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: "(crontab -l; echo '0 */12 * * * /home/website-scripts/renew.sh') | crontab -"

      - name: Execute setup script on remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}     
          script: "bash /home/website-scripts/setup.sh"
        
      - name: Execute docker compose on remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}        
          script: "cd /website-scripts && docker-compose up -d"                      
