name: Deploy Ghost Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment variables
        run: echo "${{ secrets.ENV_CONTENT }}" > .env

      - name: Copy all files to server
        uses: appleboy/scp-action@master      
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./*"
          target: "/home/website-scripts"

      # - name: Add renew script to cron
      #   run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "(crontab -l; echo '0 */12 * * * /home/website-files/renew.sh') | crontab -"

      # - name: Execute setup script on server
      #   run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash /home/setup.sh"

      # - name: Restart Docker services
      #   run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home && docker-compose up -d"
